nodeLinker: node-modules

packageExtensions:
  "@expo/cli@*":
    peerDependencies:
      expo-modules-autolinking: "*"
  "@graphql-codegen/cli@*":
    dependencies:
      "@babel/core": ^7.28.0
  "@graphql-tools/code-file-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/git-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/github-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/graphql-tag-pluck@*":
    peerDependencies:
      "@babel/core": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  babel-preset-expo@*:
    peerDependencies:
      "@babel/core": "*"
  expo-asset@*:
    peerDependencies:
      expo: "*"
  expo@*:
    peerDependencies:
      "@babel/core": "*"
  jest-expo@*:
    peerDependencies:
      "@babel/core": "*"
      jest: "*"
      react: "*"
      react-native: "*"
  react-native-codegen@*:
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  ts-jest@*:
    dependencies:
      jest-util: ^29.0.0
