packageExtensions:
  jest-expo@*:
    peerDependencies:
      react-native: "*"
      react: "*"
      jest: "*"
      "@babel/core": "*"
  ts-jest@*:
    dependencies:
      jest-util: "^29.0.0"
  "@expo/cli@*":
    peerDependencies:
      expo-modules-autolinking: "*"
  "@graphql-tools/graphql-tag-pluck@*":
    peerDependencies:
      "@babel/core": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  "babel-preset-expo@*":
    peerDependencies:
      "@babel/core": "*"
  "expo-asset@*":
    peerDependencies:
      expo: "*"
  "react-native-codegen@*":
    dependencies:
      "@babel/preset-env": "*"
      "@babel/core": "*"
  "@graphql-tools/code-file-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/git-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/github-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "expo@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-codegen/cli@*":
    dependencies:
      "@babel/core": "^7.28.0"
