name: Plugin CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TypeScript compile check (all workspaces)
        run: yarn workspaces foreach -vpt run tsc --noEmit

      - name: SDK compatibility validation
        run: yarn plugin-sdk-validate

      - name: Run unit tests
        run: yarn test
